### DISCUSSION TITLE
Alternative way of AC control

### DISCUSSION THREAD

**Discussion by mateuszdrab** [issalig/toshiba_air_cond#48] [Ideas]
Hey guys

Just wanted to share an idea as I've managed to get the control of my unit work through the AB line with a [Realtime FDP3](http://www.realtime-controls.co.uk/index.php/site/product-list/C2) gateway which I got off [eBay](https://www.ebay.co.uk/itm/395263673261) which is available for about £50. There is also a Modbus only version of the FDP3 module which surprisingly costs more despite not having the inputs for manual control. There is a chance the Modbus specific option has a better implementation of the Modbus protocol but we'll never know as it seems the company is no longer trading.

The gateway features a Modbus interface and I connected it to a Waveshare Modbus to WiFi gateway (which supports Modbus RTU to TCP gateway feature) and then I got a climate component set up in HASS using the Modbus Climate integration.

The only culprit is that the return air temperature needs to be scaled down/divided by 100 to get the right float number; however, this is not possible in the current Modbus integration so I had to manually modify the source code to do that. I plan on expanding the Modbus Climate feature for scaling that value only and PR it back.

The configuration in home assistant looks like this 
```
modbus:
  - name: modbus_hub
    type: tcp
    host: modbus-gateway
    port: 8899
    # delay: 1000
    climates:
      - name: "Toshiba AC - Living Room"
        data_type: int16
        slave: 1
        address: 123
        input_type: input
        min_temp: 17
        max_temp: 30
        scan_interval: 15
        unique_id: toshiba_ravsm806krte

        precision: 1

        target_temp_register: 101
        hvac_onoff_register: 105
        hvac_mode_register:
          address: 103
          values:
            state_heat: 1
            state_auto: 0
            state_cool: 3
            state_dry: 4
            state_fan_only: 2
        fan_mode_register:
          address: 102
          values:
            state_fan_auto: 0
            state_fan_low: 1
            state_fan_medium: 2
            state_fan_high: 3
        swing_mode_register:
          address: 104
          values:
            swing_mode_state_on: 1
            swing_mode_state_horizontal: 2
            swing_mode_state_vertical: 4
        temp_step: 1
        temperature_unit: C
```

The other issues I found is that sometimes when the unit is off, I can't seem to be able to power it on via HASS but it works fine with the wireless remote, wired remote.
When running swing mode, the wireless remote can't seem to stop it when the FDP3 unit is connected, luckily can control it via HASS but it's not as fine grained control as with the remote.
I presume the FDP3 device only handles a subset of the AB control protocol.
When trying to change too many settings on the AC at the same time, sometimes not all settings change. Presume this might be due to slowness of Modbus or something with the FDP3 device.

![image](https://github.com/user-attachments/assets/0ca7986d-e97a-4943-b4b8-082ac2484e3d)

I'm happy to share more details if anyone wants to try implement this solution as I'm quite curious if others would experience the above issues as well.

Anyways, I hope this helps as is.
